#define IGNORE_MOD_TAP_INTERRUPT
#define PERMISSIVE_HOLD
#define RETRO_TAPPING
#define TAPPING_FORCE_HOLD

#undef RGB_DISABLE_TIMEOUT
#define RGB_DISABLE_TIMEOUT 60000

#define USB_SUSPEND_WAKEUP_DELAY 0
#undef MOUSEKEY_WHEEL_DELAY
#define MOUSEKEY_WHEEL_DELAY 200

#undef MOUSEKEY_WHEEL_INTERVAL
#define MOUSEKEY_WHEEL_INTERVAL 50

#define CAPS_LOCK_STATUS
#define RGB_MATRIX_STARTUP_SPD 60

// leader key
#define LEADER_TIMEOUT 500
#define LEADER_PER_KEY_TIMING 200

// // mouse (contant mode)
// #define MK_3_SPEED
// #define MK_C_OFFSET_0 5
// #define MK_C_OFFSET_1 10
// #define MK_C_OFFSET_2 20
// #define MK_W_OFFSET_0 1
// #define MK_W_OFFSET_1 3
// #define MK_W_OFFSET_2 5
